services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<Password>
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-data/data:/var/opt/mssql/data
      - ./mssql-data/log:/var/opt/mssql/log
      - ./mssql-data/secrets:/var/opt/mssql/secrets
