services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ""
    volumes:
      - ./mssql-data/data:/var/opt/mssql/data
      - ./mssql-data/log:/var/opt/mssql/log
      - ./mssql-data/secrets:/var/opt/mssql/secrets
    ports:
      - "1433:1433"
    restart: unless-stopped
